server:
    port: ${PORT:8082}
spring:
    profiles:
        active: ${PROFILE:local}
    application:
        name: api-gateway
    config:
        fail-fast: true
        retry:
            maxAttempts: 200
            maxInterval: 10000
        import: ${CONFIG_URL:optional:configserver:http://localhost:8012}
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    banner:
        location: classpath:banner.txt

    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: az.rock.lib.kafka.json.EventSerializer
        consumer:
            auto-offset-reset: earliest
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringDeserializer
            value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
              spring:
                  json:
                      trusted:
                          packages: '*'
