server:
    port: ${PORT:8082}
spring:
    profiles:
        active: ${PROFILE:local}
    application:
        name: api-gateway
    config:
        fail-fast: true
        retry:
            maxAttempts: 200
            maxInterval: 10000
        import: ${CONFIG_URL:optional:configserver:http://localhost:8012}
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    banner:
        location: classpath:banner.txt


feign:
    client:
        config:
            default:
                connect-timeout: 5000
                read-timeout: 5000

