server:
    port: ${PORT:8082}
spring:
    profiles:
        active: ${PROFILE:local}
    application:
        name: api-gateway
    config:
        fail-fast: true
        retry:
            maxAttempts: 200
            maxInterval: 10000
        import: ${CONFIG_URL:optional:configserver:http://localhost:8012}
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
management:
    endpoints:
        web:
            exposure:
                include: '*'