server:
    port: ${PORT:0}
spring:
    application:
        name: matcher-service
    banner:
        location: classpath:banner.txt
    config:
        import: ${CONFIG_URL:configserver:http://localhost:8012}
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    profiles:
        active: ${PROFILE:local}

mybatis:
    mapper-locations:
        - classpath*:/az/rock/ws/dataAccess/repository/concretes/*.xml
