package az.rock.ws.dataAccess.entity;

import java.util.Date;

public class UserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.uuid
     *
     * @mbg.generated
     */
    private Object uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.modification_date
     *
     * @mbg.generated
     */
    private Date modificationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.key
     *
     * @mbg.generated
     */
    private Object key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.role
     *
     * @mbg.generated
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_list.profile_uuid
     *
     * @mbg.generated
     */
    private Object profileUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.uuid
     *
     * @return the value of users.users_list.uuid
     *
     * @mbg.generated
     */
    public Object getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.uuid
     *
     * @param uuid the value for users.users_list.uuid
     *
     * @mbg.generated
     */
    public void setUuid(Object uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.created_date
     *
     * @return the value of users.users_list.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.created_date
     *
     * @param createdDate the value for users.users_list.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.modification_date
     *
     * @return the value of users.users_list.modification_date
     *
     * @mbg.generated
     */
    public Date getModificationDate() {
        return modificationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.modification_date
     *
     * @param modificationDate the value for users.users_list.modification_date
     *
     * @mbg.generated
     */
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.email
     *
     * @return the value of users.users_list.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.email
     *
     * @param email the value for users.users_list.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.first_name
     *
     * @return the value of users.users_list.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.first_name
     *
     * @param firstName the value for users.users_list.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.key
     *
     * @return the value of users.users_list.key
     *
     * @mbg.generated
     */
    public Object getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.key
     *
     * @param key the value for users.users_list.key
     *
     * @mbg.generated
     */
    public void setKey(Object key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.last_name
     *
     * @return the value of users.users_list.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.last_name
     *
     * @param lastName the value for users.users_list.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.password
     *
     * @return the value of users.users_list.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.password
     *
     * @param password the value for users.users_list.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.role
     *
     * @return the value of users.users_list.role
     *
     * @mbg.generated
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.role
     *
     * @param role the value for users.users_list.role
     *
     * @mbg.generated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.username
     *
     * @return the value of users.users_list.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.username
     *
     * @param username the value for users.users_list.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_list.profile_uuid
     *
     * @return the value of users.users_list.profile_uuid
     *
     * @mbg.generated
     */
    public Object getProfileUuid() {
        return profileUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_list.profile_uuid
     *
     * @param profileUuid the value for users.users_list.profile_uuid
     *
     * @mbg.generated
     */
    public void setProfileUuid(Object profileUuid) {
        this.profileUuid = profileUuid;
    }
}