server:
  port: ${PORT:0}
spring:
  config:
    import: ${CONFIG_URL:configserver:http://localhost:8012}
  application:
    name: user-profile-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: ${PROFILE:local}
