spring:
    application:
        name: user-profile-service
    config:
        import: ${CONFIG_URL:configserver:http://localhost:8012}
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    profiles:
        active: ${PROFILE:local}
