server:
  port: ${PORT:8012}

spring:
  application:
    name: config-service
  profiles:
    active: ${PROFILE:local}
  cloud:
    config:
      server:
        git:
          default-label: ${GIT_BRANCH:main}
          password: ${GIT_PASS}
          username: ${GIT_NAME}
          clone-on-start: true
          uri: ${GIT_ADDRESS}

